
import React from 'react';
import { Invoice } from '../types';
import { translations } from '../translations';

interface InvoicePrintViewProps {
  invoice: Invoice;
  lang: 'bn' | 'en';
}

const InvoicePrintView: React.FC<InvoicePrintViewProps> = ({ invoice, lang }) => {
  const t = translations[lang];

  return (
    <div id="invoice-print-area" className="p-12 text-black bg-white min-h-screen">
      <div className="flex justify-between items-start border-b-2 border-indigo-600 pb-8 mb-12">
        <div>
          <h1 className="text-4xl font-black text-indigo-600 mb-2">{t.appName}</h1>
          <p className="text-sm text-gray-500 italic">{t.appSubName}</p>
        </div>
        <div className="text-right">
          <h2 className="text-2xl font-bold uppercase tracking-widest text-gray-400">INVOICE</h2>
          <p className="text-lg font-bold"># {invoice.invoiceNumber}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-12 mb-12">
        <div>
          <h3 className="text-xs font-bold uppercase text-gray-400 mb-2">{t.billFrom}</h3>
          <p className="whitespace-pre-wrap text-sm leading-relaxed">{invoice.billFrom}</p>
        </div>
        <div className="text-right">
          <h3 className="text-xs font-bold uppercase text-gray-400 mb-2">{t.billTo}</h3>
          <p className="whitespace-pre-wrap text-sm leading-relaxed">{invoice.billTo}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-12 bg-gray-50 p-4 rounded-xl border border-gray-100">
        <div>
          <span className="text-xs font-bold text-gray-400 mr-2 uppercase">{t.date}:</span>
          <span className="text-sm font-bold">{invoice.date}</span>
        </div>
        <div className="text-right">
          <span className="text-xs font-bold text-gray-400 mr-2 uppercase">{t.dueDate}:</span>
          <span className="text-sm font-bold text-red-600">{invoice.dueDate}</span>
        </div>
      </div>

      <table className="w-full mb-12">
        <thead>
          <tr className="bg-indigo-600 text-white text-sm">
            <th className="p-4 text-left rounded-tl-xl">{t.items}</th>
            <th className="p-4 text-center">{t.quantity}</th>
            <th className="p-4 text-right">{t.rate}</th>
            <th className="p-4 text-right rounded-tr-xl">{t.amount}</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100 border-x border-b border-gray-100 rounded-b-xl overflow-hidden">
          {invoice.items.map((item, idx) => (
            <tr key={idx} className="text-sm">
              <td className="p-4 font-medium">{item.description}</td>
              <td className="p-4 text-center">{item.quantity}</td>
              <td className="p-4 text-right">{item.rate.toFixed(2)}</td>
              <td className="p-4 text-right font-bold">{item.amount.toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="flex justify-end mb-12">
        <div className="w-1/3 space-y-3">
          <div className="flex justify-between text-sm text-gray-600">
            <span>{t.subtotal}</span>
            <span className="font-bold">{invoice.subtotal.toFixed(2)}</span>
          </div>
          <div className="flex justify-between text-sm text-gray-600">
            <span>{t.tax} ({invoice.taxRate}%)</span>
            <span className="font-bold">{invoice.taxAmount.toFixed(2)}</span>
          </div>
          <div className="flex justify-between text-xl font-black text-indigo-600 border-t-2 border-indigo-100 pt-3">
            <span>{t.total}</span>
            <span>{invoice.total.toFixed(2)}</span>
          </div>
        </div>
      </div>

      {invoice.notes && (
        <div className="border-t border-gray-100 pt-8">
          <h4 className="text-xs font-bold text-gray-400 uppercase mb-2">{t.notes}</h4>
          <p className="text-sm text-gray-600 leading-relaxed italic">{invoice.notes}</p>
        </div>
      )}

      <div className="fixed bottom-12 left-0 w-full text-center text-[10px] text-gray-300 uppercase tracking-widest pointer-events-none">
        Generated by {t.appName}
      </div>
    </div>
  );
};

export default InvoicePrintView;
